[build-system]
requires = ["setuptools>=64", "setuptools_scm[toml]>=7.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nirscloud_legacy"
authors = [{ name = "Julia Tatz", email = "julia.tatz@childrens.harvard.edu" }]
requires-python = ">=3.13"
dynamic = ["version"]
dependencies = [
    "numpy>=1.23",
    "xarray>=0.19",
    "pymongo>=3.12",
    "pandas>=1.2",
    "pyarrow>=12",
    "fsspec",
    "metaox_parser@git+https://github.com/jdtatz/metaox_parser.git",
]

[tool.setuptools_scm]
write_to = "nirscloud_legacy/_version.py"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
# https://docs.astral.sh/ruff/rules/
extend-select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # Pylint
    "PL",
    # pyupgrade
    "UP",
    # Ruff-specific rules
    "RUF",
    # NumPy-specific rules
    "NPY",
    # flake8-bugbear
    "B",
    # flake8-comprehensions
    "C4",
    # flake8-boolean-trap
    "FBT",
    # flake8-return
    "RET",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = [
    # multiple-leading-hashes-for-block-comment
    "E266",
    # line-too-long
    "E501",
    # no-explicit-stacklevel
    "B028",
    # redundant-open-modes
    "UP015",
    # non-pep604-annotation-optional
    "UP045",
    # non-pep695-generic-function
    "UP047",
    # unnecessary-assign
    "RET504",
    # superfluous-else-return 
    "RET505",
    # superfluous-else-raise
    "RET506",
    # too-many-branches
    "PLR0912",
    # too-many-arguments 
    "PLR0913",
    # too-many-statements
    "PLR0915",
    # magic-value-comparison
    "PLR2004",
]
