[tool.poetry]
name = "nirscloud-julia"
version = "0.1.15"
description = "Julia's nirscloud utils"
authors = ["Julia Tatz <tatz.j@northeastern.edu>"]
include = ["nirscloud_julia/*.py", "nirscloud_julia/nirs_bokeh_theme.yml"]

[tool.poetry.dependencies]
python = ">=3.7.1"
numpy = "~1.20"
scipy = "~1.6"
numpy-quaternion = ">=2021.7"
xarray = "~0.19"
pymongo = "~3.0"
matplotlib = "~3.4"
pandas = "~1.2"
zarr = "~2.8"
requests = "~2.26"
hdfs = "~2.6"
requests-gssapi = "~1.2"
pyarrow = ">=4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
