from pathlib import PurePosixPath

KAFKA_TOPICS_FT = "fastrak2_s"
KAFKA_TOPICS_FT_CM = "fastrak_cm_s"
KAFKA_TOPICS_N = "metaox_nirs_rs"
KAFKA_TOPICS_D = "metaox_dcs_s"
KAFKA_TOPICS_FP = "finapres_waveform_s"
KAFKA_TOPICS_FP_2 = "finapres_waveform2_s"
KAFKA_TOPICS_FP_3 = "finapres_waveform_su"
KAFKA_TOPICS_PM = "ixtrend_waves5_s"
KAFKA_TOPICS_PM_N = "ixtrend_numerics2_s"

FASTRAK_KAFKA_TOPICS = KAFKA_TOPICS_FT_CM, KAFKA_TOPICS_FT
NIRS_KAFKA_TOPICS = (KAFKA_TOPICS_N,)
DCS_KAFKA_TOPICS = (KAFKA_TOPICS_D,)
FINAPRES_KAFKA_TOPICS = KAFKA_TOPICS_FP_3, KAFKA_TOPICS_FP_2, KAFKA_TOPICS_FP
PM_KAFKA_TOPICS = "ixtrend_waves5_s", "ixtrend_waves4_s", "ixtrend_waves3_s", "ixtrend_waves2_s", "ixtrend_waves"
PM_N_KAFKA_TOPICS = "ixtrend_numerics2_s", "ixtrend_numerics_s", "ixtrend_numerics"

HDFS_NAMESERVICE = "BabyNIRSHDFS"
HDFS_PREFIX_DEDUP = PurePosixPath("/nirscloud/dedup")
HDFS_PREFIX_AGG_HR = PurePosixPath("/nirscloud/agg_by_hr")
HDFS_PREFIX_AGG_DAY = PurePosixPath("/nirscloud/agg_by_day")
HDFS_PREFIX_AGG = PurePosixPath("/nirscloud/agg")
HDFS_PREFIX_AGG_HR = PurePosixPath("/nirscloud/agg_by_hr")
HDFS_PREFIX_AGG_HR2 = PurePosixPath("/nirscloud/agg_by_hr2")
HDFS_PREFIX_AGG_HR3 = PurePosixPath("/nirscloud/agg_by_hr3")
HDFS_PREFIX_AGG_DAY = PurePosixPath("/nirscloud/agg_by_day")
HDFS_PREFIX_KAFKA_TOPICS = PurePosixPath("/kafka/topics")
HDFS_PREFIX = HDFS_PREFIX_AGG

HDFS_PREFIX_FT = HDFS_PREFIX_AGG / KAFKA_TOPICS_FT
HDFS_PREFIX_FT_CM = HDFS_PREFIX_AGG / KAFKA_TOPICS_FT_CM
HDFS_PREFIX_N = HDFS_PREFIX_DEDUP / KAFKA_TOPICS_N
HDFS_PREFIX_D = HDFS_PREFIX_DEDUP / KAFKA_TOPICS_D
HDFS_PREFIX_FP = HDFS_PREFIX_DEDUP / KAFKA_TOPICS_FP
HDFS_PREFIX_FP_2 = HDFS_PREFIX_AGG / KAFKA_TOPICS_FP_2
HDFS_PREFIX_FP_3 = HDFS_PREFIX_AGG / KAFKA_TOPICS_FP_3
HDFS_PREFIX_PM = HDFS_PREFIX_AGG / KAFKA_TOPICS_PM
HDFS_PREFIX_PM_N = HDFS_PREFIX_AGG / KAFKA_TOPICS_PM_N

HDFS_FASTRAK_PREFIXES = HDFS_PREFIX_FT_CM, HDFS_PREFIX_FT, HDFS_PREFIX_DEDUP / "fastrak_s"
HDFS_NIRS_PREFIXES = (HDFS_PREFIX_N,)
HDFS_DCS_PREFIXES = (HDFS_PREFIX_D,)
HDFS_FINAPRES_PREFIXES = HDFS_PREFIX_FP_3, HDFS_PREFIX_FP_2, HDFS_PREFIX_FP
HDFS_PM_PREFIXES = (HDFS_PREFIX_PM, *(HDFS_PREFIX_DEDUP / t for t in PM_KAFKA_TOPICS))
HDFS_PM_N_PREFIXES = (HDFS_PREFIX_PM_N, *(HDFS_PREFIX_DEDUP / t for t in PM_N_KAFKA_TOPICS))


PATIENT_MONITOR_COMPONENT_MAPPING = {
    0x013D: "III",
    0x0102: "II",
    0x013E: "aVR",
    0x0140: "aVF",
    0x4BB4: "Pleth",
    0x4A14: "ABP",
    0x5000: "Resp",
    0x0104: "Compound ECG-II",
    0x4182: "HR",
    0x4A05: "NBP-SYS",
    0x4A06: "NBP-DIA",
    0x4A07: "NBP-MEAN",
    0x4BB8: "SpO2",
    0x4822: "Pulse.1",
    0x500A: "RR",
    0x4BB0: "Perf-REL",
    0x480A: "Pulse",
}
